### ISSUE TITLE
URDF dynamical parameters tuning for flying

### ISSUE THREAD

**Issue by avikde** [avikde/robobee3d#4]
Should probably happen after #2 

- [x] scale correct, rough aero forces correct #6 
- [x] flapping kinematics #11
- [x] Flying in pybullet #13
- [x] stroke to force control #14
